# Generated by Django 3.0.5 on 2021-03-21 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='qusform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qno', models.IntegerField()),
                ('qus', models.TextField()),
                ('op1', models.CharField(max_length=1000)),
                ('op2', models.CharField(max_length=1000)),
                ('op3', models.CharField(max_length=1000)),
                ('op4', models.CharField(max_length=1000)),
            ],
        ),
    ]
