# Generated by Django 3.0.5 on 2021-03-28 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='allans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qusno', models.IntegerField()),
                ('qus', models.CharField(max_length=1000)),
                ('ans', models.CharField(max_length=1000)),
            ],
        ),
    ]
